spring:
  application:
    name: zuul-api-gateway
server:
  port: 8765


zuul:
  routes:
    contact-book:
      path: /contact-book
      url: forward:/
  ratelimit:
    enabled: true
    repository: JPA
    policy-list:
      contact-book:
      - limit: 2
        refresh-interval: 60
        type:
        - origin
  strip-prefix: true